language: ruby
rbenv:
- 3.0.0
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: HEROKU_DEPLOY_KEY
  app: https://git.heroku.com/getbelayed.git
  on:
    repo: PhilipDeFraties/GetBelayed
  run: rails db:migrate
